06 task -
mollybrace/nc-news pull request #4
Opened 2023-03-14 08:45 UTC by mollybrace

Tasks completed up to ticket 7  vote on article.

2023-03-14 09:33 UTC, Jodiech requested changes
Hey Molly 😄 well done on the tickets! For ticket 7 I'd recommend adding functionality so the voter can only vote once in either direction. I've left a comment for adding visual feedback for the user if the data is loading. I'd add a message for the user if the patch request fails. Well done! 🚀

2023-03-14 09:33 UTC, Jodiech commented on src/components/comments.jsx
> +
Consider adding visual feedback if data is still loading for the user 👍

2023-03-14 09:33 UTC, Jodiech commented on src/components/articleelement.jsx
>                          </li>
Nice to see the vote updating immediately with optimistic rendering 👍 You could also add a downvote as well. Just a suggestion but something to think about for your app 😄

2023-03-14 09:33 UTC, Jodiech commented on src/components/articleelement.jsx
> +    patchArticleVotes(article_id)
Consider adding a message for the user if the patch request fails.

2023-03-16 09:07 UTC, Harrison365 commented
Hey Molly :) 

This is looking good 👍 

Please could you take a look at the following:
- ensure that people can't post an empty comment (optimistically). E.g. give an error message.
- forms should be cleared after submit.
- user should be given feedback after a successful or unsuccessful post 
- the comment section should be multi-line (e.g. text-area not input)

Please let us know when you'd like us to take another look 🙂

2023-03-16 13:56 UTC, robert112233 commented
Your search by topic is working great! You might want to add an isLoading in between the searches to show the user that something is taking place under the hood. 

I'm not sure if you needed comment submission reviewing but they aren't working as expected still. When I try to submit a blank comment I get "comment submitted successfully" _and_ an error message. And then when I do submit a valid comment, the error message from before still persists. I've attached screenshots to show this behaviour. 

<img width="355" alt="Screenshot 2023-03-16 at 13 50 06" src="https://user-images.githubusercontent.com/106443136/225639490-ab6656d9-a202-4392-87de-9d2f0e511067.png">
<img width="395" alt="Screenshot 2023-03-16 at 13 51 53" src="https://user-images.githubusercontent.com/106443136/225639659-3497c639-cfb2-47bc-b38e-6bd1524a7230.png">

2023-03-17 10:40 UTC, mollybrace commented on src/components/articleelement.jsx
>                          </li>
completed

2023-03-17 11:12 UTC, Jodiech commented on src/components/articleelement.jsx
>                          </li>
Hey Molly, Great that you have put in the functionality for upvoting and downvoting. I'd change these to buttons as it's unclear to see if they are two separate things. You could disable one of the buttons when one is clicked to show the user they have pressed it. Hope this makes sense, let me know if you need help with anything 😄

2023-03-17 13:47 UTC, merged